title: The Country Shed UK
description: Faceless UK guides to farming tools, country gear and country wear.
baseurl: ""
url: "https://country-shed-uk.github.io"
theme: minima
author: The Country Shed Team
plugins:
  - jekyll-feed

# Affiliate settings
amazon_tag: countrysheduk-21
currency: "£"

# Build settings
markdown: kramdown