title: The Country Shed UK
description: Faceless UK guides to farming tools, country gear and country wear.
baseurl: ""
url: "https://YOUR_USERNAME.github.io"
theme: minima
author: Country Shed Team
plugins:
  - jekyll-feed

# Affiliate settings
amazon_tag: YOUR_AMAZON_TAG  # e.g. yourtag-21
currency: "£"

# Build settings
markdown: kramdown